"""Fail2ban brute-force jails for the mail server (serverkit-mail extension).

Mirrors the core :class:`Fail2banJailService` write-half pattern: ServerKit-owned
``serverkit-mail-*`` jail files under ``/etc/fail2ban/jail.d``, written with
privilege (``sudo tee``), reloaded via ``fail2ban-client reload``.

The auth jail watches the mail auth log for repeated SMTP/IMAP login failures and
bans the offending IP. Best-effort and Linux-only: on Windows (dev) or when
fail2ban is absent, every mutating call returns a ``skipped`` descriptor instead
of raising, so mail setup degrades gracefully.
"""
import logging
import os

from app.utils.system import run_privileged, is_command_available, ServiceControl

logger = logging.getLogger(__name__)


class MailJailService:
    JAIL_DIR = '/etc/fail2ban/jail.d'
    JAIL_PREFIX = 'serverkit-mail-'
    AUTH_JAIL = 'serverkit-mail-auth'

    # 5 auth failures within 10 min -> 1 hour ban.
    MAXRETRY = 5
    FINDTIME = 600
    BANTIME = 3600

    # Stalwart writes its log inside the container data dir bind-mounted to the
    # host; fall back to the common dovecot/postfix filters if present. The jail
    # uses the stock filters so it works without a custom filter file.
    LOG_PATH = '/var/serverkit/mail/logs/stalwart.log'

    JAIL_TEMPLATE = '''# ServerKit-managed mail brute-force jail.
# Generated by MailJailService - do not edit by hand (regenerated on change).
[{jail}]
enabled = true
filter = {filter}
port = smtp,submission,smtps,imap,imaps,pop3,pop3s
logpath = {logpath}
maxretry = {maxretry}
findtime = {findtime}
bantime = {bantime}
'''

    # ---------- availability ----------

    @classmethod
    def available(cls):
        """True only on a Linux host where the fail2ban client is installed."""
        if os.name == 'nt':
            return False
        return is_command_available('fail2ban-client')

    @staticmethod
    def _unavailable():
        return {
            'success': True, 'skipped': True, 'available': False, 'reason': 'unavailable',
            'message': 'fail2ban is not available on this host; mail brute-force '
                       'protection is inactive.',
        }

    # ---------- file helpers ----------

    @classmethod
    def _jail_path(cls):
        filename = f'{cls.AUTH_JAIL}.conf'
        if (not filename.startswith(cls.JAIL_PREFIX)
                or '/' in filename or '\\' in filename or '..' in filename):
            raise ValueError(f'refusing to target non-ServerKit jail file: {filename!r}')
        return os.path.join(cls.JAIL_DIR, filename)

    @staticmethod
    def _write_file(path, content):
        """Write *content* to *path* with privilege (sudo tee)."""
        try:
            proc = run_privileged(['tee', path], input=content)
            if getattr(proc, 'returncode', 1) != 0:
                return {'success': False, 'error': (getattr(proc, 'stderr', '') or 'write failed').strip()}
            return {'success': True, 'path': path}
        except Exception as e:  # noqa: BLE001
            return {'success': False, 'error': str(e)}

    @classmethod
    def _render_jail(cls):
        return cls.JAIL_TEMPLATE.format(
            jail=cls.AUTH_JAIL,
            filter='postfix-sasl',  # stock filter; broadly present on Debian/RHEL
            logpath=cls.LOG_PATH,
            maxretry=cls.MAXRETRY,
            findtime=cls.FINDTIME,
            bantime=cls.BANTIME,
        )

    # ---------- jail lifecycle ----------

    @classmethod
    def enable_auth_jail(cls):
        """Create/refresh the mail auth brute-force jail and reload fail2ban."""
        if not cls.available():
            return cls._unavailable()
        try:
            path = cls._jail_path()
        except ValueError as e:
            return {'success': False, 'error': str(e)}
        written = cls._write_file(path, cls._render_jail())
        if not written.get('success'):
            return written
        reloaded = cls.reload()
        return {'success': True, 'enabled': True, 'jail': cls.AUTH_JAIL,
                'path': path, 'reloaded': reloaded.get('success')}

    @classmethod
    def disable_auth_jail(cls):
        """Remove the mail auth jail file and reload fail2ban. No-op when absent."""
        if not cls.available():
            return cls._unavailable()
        try:
            path = cls._jail_path()
        except ValueError as e:
            return {'success': False, 'error': str(e)}
        if not os.path.exists(path):
            return {'success': True, 'removed': False, 'message': 'no jail to remove'}
        try:
            proc = run_privileged(['rm', '-f', path])
            if getattr(proc, 'returncode', 1) != 0:
                return {'success': False, 'error': (getattr(proc, 'stderr', '') or 'remove failed').strip()}
        except Exception as e:  # noqa: BLE001
            return {'success': False, 'error': str(e)}
        reloaded = cls.reload()
        return {'success': True, 'removed': True, 'jail': cls.AUTH_JAIL,
                'reloaded': reloaded.get('success')}

    @classmethod
    def reload(cls):
        """``fail2ban-client reload`` (keeps existing bans), falling back to a
        service restart if the client call fails. Never raises."""
        if not cls.available():
            return cls._unavailable()
        try:
            proc = run_privileged(['fail2ban-client', 'reload'], timeout=30)
            if getattr(proc, 'returncode', 1) == 0:
                return {'success': True, 'message': 'fail2ban reloaded'}
        except Exception:
            pass
        try:
            res = ServiceControl.restart('fail2ban', timeout=30)
            return {'success': getattr(res, 'returncode', 1) == 0,
                    'message': 'fail2ban restarted' if getattr(res, 'returncode', 1) == 0
                    else (getattr(res, 'stderr', '') or 'reload failed')}
        except Exception as e:  # noqa: BLE001
            return {'success': False, 'error': str(e)}

    @classmethod
    def status(cls):
        """Availability + whether the auth jail file exists."""
        info = {'available': cls.available(), 'enabled': False, 'jail': cls.AUTH_JAIL}
        if not cls.available():
            return info
        try:
            info['enabled'] = os.path.exists(cls._jail_path())
        except ValueError:
            info['enabled'] = False
        return info
